# Generated by Django 2.2.2 on 2020-05-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0014_auto_20200513_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudevent',
            name='object_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
