# Generated by Django 5.0.1 on 2024-03-18 19:53
#
# NOTE (pipefile fork): The auto-generated form of this migration flipped
# several columns from NULL -> NOT NULL with a plain `AlterField`, which emits
# `ALTER COLUMN ... SET NOT NULL`. On Postgres that takes an ACCESS EXCLUSIVE
# lock and full-table scan. On the *hot* `requestevent` table (written on most
# requests via EasyAuditMiddleware) that lock can never be acquired against the
# live write stream, so the production deploy hangs indefinitely. See
# docs/incidents/2026-06-15-easyaudit-0019-migration-hang.md in pipefile_web.
#
# This rewrite reaches the IDENTICAL end-state (same columns, types, nullability,
# indexes) but performs the `requestevent` NOT NULL changes ONLINE via the
# standard `ADD CONSTRAINT ... NOT VALID` -> `VALIDATE` -> `SET NOT NULL` pattern
# (validation scans under SHARE UPDATE EXCLUSIVE, which does NOT block writes).
# `crudevent`/`loginevent` are static / low-volume, so their `AlterField`s are
# left as-is (with a cheap NULL backfill as insurance against a NULL-value error
# on populated tables). `atomic = False` is required so the online steps commit
# independently and locks are not held across the scan.
#
# The squashed migration (0004_..._squashed_0019...) is intentionally left
# unchanged: it only ever runs against a fresh, EMPTY database (CI / new clones),
# where blocking SET NOT NULL is instant. Only this individual migration runs on
# the populated production database.

from django.db import migrations, models


def _online_set_not_null(table, column):
    """Forward DB operations to set a column NOT NULL without blocking writes."""
    constraint = f"_tmp_nn_{table}_{column}"
    return [
        # 1. Backfill any NULLs (safety; staging had none, prod may have legacy rows).
        migrations.RunSQL(
            sql=f"UPDATE {table} SET {column} = '' WHERE {column} IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 2. Add the NOT NULL guarantee as an unvalidated CHECK (instant once the lock
        #    is held). lock_timeout makes acquisition FAIL FAST (deploy aborts cleanly)
        #    rather than hang if some long-lived transaction is camped on the table.
        migrations.RunSQL(
            sql=(
                f"SET lock_timeout = '5s'; "
                f'ALTER TABLE {table} ADD CONSTRAINT "{constraint}" CHECK ({column} IS NOT NULL) NOT VALID; '
                f"RESET lock_timeout;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 3. Validate it -- scans under SHARE UPDATE EXCLUSIVE, does NOT block reads/writes.
        migrations.RunSQL(
            sql=f'ALTER TABLE {table} VALIDATE CONSTRAINT "{constraint}";',
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 4. Set NOT NULL -- PG12+ reuses the validated constraint, so this is fast (no
        #    re-scan). Again guarded by lock_timeout so it can never hang on the lock.
        migrations.RunSQL(
            sql=(
                f"SET lock_timeout = '5s'; "
                f"ALTER TABLE {table} ALTER COLUMN {column} SET NOT NULL; "
                f"RESET lock_timeout;"
            ),
            reverse_sql=f"ALTER TABLE {table} ALTER COLUMN {column} DROP NOT NULL;",
        ),
        # 5. Drop the now-redundant CHECK.
        migrations.RunSQL(
            sql=f'ALTER TABLE {table} DROP CONSTRAINT "{constraint}";',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]


class Migration(migrations.Migration):

    # Required for the online (multi-statement, independently-committed) DDL below.
    atomic = False

    dependencies = [
        ('easyaudit', '0018_rename_crudevent_object_id_content_type_index'),
    ]

    operations = [
        # --- crudevent (static since CRUD auditing was disabled; no write contention) ---
        # Django's AlterField for a null->NOT NULL change already emits its own
        # `UPDATE ... WHERE col IS NULL` backfill before `SET NOT NULL`, so no
        # explicit backfill is needed here. These run as ordinary (blocking)
        # `SET NOT NULL` -- safe because crudevent is static (no live writers).
        migrations.AlterField(
            model_name='crudevent',
            name='changed_fields',
            field=models.TextField(blank=True, default='', verbose_name='Changed fields'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='object_json_repr',
            field=models.TextField(blank=True, default='', verbose_name='Object JSON representation'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='object_repr',
            field=models.TextField(blank=True, default='', verbose_name='Object representation'),
        ),
        migrations.AlterField(
            model_name='crudevent',
            name='user_pk_as_string',
            field=models.CharField(blank=True, default='', help_text='String version of the user pk', max_length=255, verbose_name='User PK as string'),
        ),
        # --- loginevent (low volume; only written on auth events) ---
        # Same as crudevent: AlterField backfills NULLs itself; ordinary SET NOT
        # NULL is fine on this small, low-write table.
        migrations.AlterField(
            model_name='loginevent',
            name='remote_ip',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Remote IP'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Username'),
        ),
        # --- requestevent (HOT table: written on nearly every request) ---
        # Index on remote_ip already exists (db_index since migration 0006), so no
        # index build here -- only the NOT NULL change, done ONLINE to avoid the hang.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='requestevent',
                    name='query_string',
                    field=models.TextField(default='', verbose_name='Query string'),
                ),
            ],
            database_operations=_online_set_not_null('easyaudit_requestevent', 'query_string'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='requestevent',
                    name='remote_ip',
                    field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Remote IP'),
                ),
            ],
            database_operations=_online_set_not_null('easyaudit_requestevent', 'remote_ip'),
        ),
    ]
